sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t markhary/udemy-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true markhary/udemy-react-test npm test -- --coverage

after_success:
  - docker build -t markhary/udemy-multi-client -f ./client ./client
  - docker build -t markhary/udemy-multi-nginx -f ./nginx ./nginx
  - docker build -t markhary/udemy-multi-server -f ./server ./server
  - docker build -t markhary/udemy-multi-worker -f ./worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to docker hub
  - docker push markhary/udemy-multi-client
  - docker push markhary/udemy-multi-nginx
  - docker push markhary/udemy-multi-server
  - docker push markhary/udemy-multi-worker
